<a href="https://colab.research.google.com/github/CSheppardCodes/Scholastic-Study-of-Data-Science/blob/main/Basic-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
arr = np.linspace(0.0, 10.0, 6).reshape(2, 3)

In [ ]:
import numpy as np

In [ ]:
arr[1][2]

10.0

In [ ]:
arr[0,1]

2.0

In [ ]:
arr

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

In [ ]:
np.matrix(np.identity(3))

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#a.shape
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:2,1:3]#[top:bottom), [left:right)



array([[2, 3],
       [6, 7]])

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6]], dtype=np.float64)

In [ ]:
x + y

array([[ 6.,  8.],
       [ 8., 10.]])

In [ ]:
a = np.arange(0,6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
a = np.arange(0,6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

In [ ]:
np.dot(a, b)

ValueError: ignored

In [ ]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [ ]:
j*j

array([[0., 1.],
       [1., 0.]])

In [ ]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

j

array([[ 0., -1.],
       [ 1.,  0.]])

In [ ]:
j.dot(j)

array([[-1.,  0.],
       [ 0., -1.]])